name: quick_insure
description: An insurance premium calculator app.
publish_to: "none"
version: 2.0.1+2

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  pdf: ^3.10.7
  printing: ^5.11.0
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.1.11
  github: ^9.13.0
  flutter_markdown_plus: ^1.0.7 # Replaces flutter_markdown

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.20

flutter_native_splash:
  color: "#C53030" # Your primary brand color
  image: assets/icon.png # Optional logo (place it in the assets folder)
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
